# ====================================================================
# docker-compose.yml
# ====================================================================
version: '3.8'

services:
  snaptube-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE=524288000  # 500MB
      - CLEANUP_INTERVAL=3600    # 1 hour
    volumes:
      - ./cookies:/app/cookies:ro
      - /tmp/snaptube:/tmp/snaptube
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future feature)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
