services:
  - type: web
    name: snapnosh-backend
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    branch: main            # Cambia al branch que uses en Git
    plan: free               # Puedes cambiar a starter o profesional si quieres más recursos
    envVars:
      - key: PORT
        value: "8000"        # Render sobrescribirá con el puerto real en producción
      - key: HOST
        value: "0.0.0.0"
      - key: YOUTUBE_COOKIES_PATH
        value: "/app/cookies/cookies.txt"
    healthCheckPath: "/api/v1/health"
    buildCommand: ""         # Usamos el Dockerfile, no es necesario comando adicional
    startCommand: ""         # El CMD del Dockerfile se usará automáticamente

#volumes:
#  - ./cookies:/app/cookies:ro        # Monta carpeta local cookies en contenedor
#  - /tmp/snaptube:/tmp/snaptube      # Monta temp local en temp del contenedor
